import * as CreatorAlias from './Creator';
import * as HomeAlias from './Home';
import * as LoginAlias from './Login';
import * as SettingAlias from './Setting';
import * as UserAlias from './User';
import * as ArticleAlias from './Article';
import * as WriteAlias from './Write';
import * as PublishAlias from './Publish';
import * as CompositionAlias from './Composition';
import * as SystemMessageAlias from './SystemMessage';
import * as UserInfoSettingAlias from './UserInfoSetting';
import * as SecuritySettingAlias from './SecuritySetting';
import * as PasswordChangeSettingAlias from './PasswordChangeSetting';
import * as AboutAlias from './About';
import * as HelpAlias from './Help';
import * as FeedbackAlias from './Feedback';
import * as HistoryAlias from './History';
import * as CommentAlias from './Comment';
import * as SupportAlias from './Support';
import * as FavoriteAlias from './Favorite';

export const Creator = CreatorAlias.default;
export const Home = HomeAlias.default;
export const Login = LoginAlias.default;
export const Setting = SettingAlias.default;
export const User = UserAlias.default;
export const Article = ArticleAlias.default;
export const Write = WriteAlias.default;
export const Publish = PublishAlias.default;
export const Composition = CompositionAlias.default;
export const SystemMessage = SystemMessageAlias.default;
export const UserInfoSetting = UserInfoSettingAlias.default;
export const SecuritySetting = SecuritySettingAlias.default;
export const PasswordChangeSetting = PasswordChangeSettingAlias.default;
export const About = AboutAlias.default;
export const Help = HelpAlias.default;
export const Feedback = FeedbackAlias.default;
export const History = HistoryAlias.default;
export const Comment = CommentAlias.default;
export const Support = SupportAlias.default;
export const Favorite = FavoriteAlias.default;
