import * as CreatorAlias from './Creator';
import * as HomeAlias from './Home';
import * as LoginAlias from './Login/Login';
import * as MessageAlias from './Message';
import * as SettingAlias from './Setting/Setting';
import * as UserAlias from './User';
import * as ArticleAlias from './Article';
import * as WriteAlias from './Write';
import * as PublishAlias from './Publish';
import * as CompositionAlias from './Composition';

export const Creator = CreatorAlias.default;
export const Home = HomeAlias.default;
export const Login = LoginAlias.default;
export const Message = MessageAlias.default;
export const Setting = SettingAlias.default;
export const User = UserAlias.default;
export const Article = ArticleAlias.default;
export const Write = WriteAlias.default;
export const Publish = PublishAlias.default;
export const Composition = CompositionAlias.default;
